---
  - name: "React with Change Example - with a Change Handler"
    hosts: logicservers
    serial: 1

    tasks:

      - name: "Install nginx"
        debug:
          msg: "Install nginx on {{ inventory_hostname }}"

      - name: "Upgrade nginx"
        debug:
          msg: "Upgrade nginx on {{ inventory_hostname }}"

      - name: "Configure nginx"
        debug:
          msg: "Configure nginx on {{ inventory_hostname }}"
        notify: restart nginx
        changed_when: True

      - name: "Verify nginx"
        debug:
          msg: "Verify nginx on {{ inventory_hostname }}"

    handlers:
    - name: restart nginx
      debug:
        msg: "CALLED HANDLER FOR RESTART"
